/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ImportRouteImport } from './routes/import'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeckDeckIdRouteImport } from './routes/deck.$deckId'
import { Route as StudyDeckIdTypingRouteImport } from './routes/study.$deckId.typing'
import { Route as StudyDeckIdReviewRouteImport } from './routes/study.$deckId.review'
import { Route as StudyDeckIdQuizRouteImport } from './routes/study.$deckId.quiz'
import { Route as StudyDeckIdFlashcardRouteImport } from './routes/study.$deckId.flashcard'

const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckDeckIdRoute = DeckDeckIdRouteImport.update({
  id: '/deck/$deckId',
  path: '/deck/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyDeckIdTypingRoute = StudyDeckIdTypingRouteImport.update({
  id: '/study/$deckId/typing',
  path: '/study/$deckId/typing',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyDeckIdReviewRoute = StudyDeckIdReviewRouteImport.update({
  id: '/study/$deckId/review',
  path: '/study/$deckId/review',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyDeckIdQuizRoute = StudyDeckIdQuizRouteImport.update({
  id: '/study/$deckId/quiz',
  path: '/study/$deckId/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyDeckIdFlashcardRoute = StudyDeckIdFlashcardRouteImport.update({
  id: '/study/$deckId/flashcard',
  path: '/study/$deckId/flashcard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/review': typeof ReviewRoute
  '/deck/$deckId': typeof DeckDeckIdRoute
  '/study/$deckId/flashcard': typeof StudyDeckIdFlashcardRoute
  '/study/$deckId/quiz': typeof StudyDeckIdQuizRoute
  '/study/$deckId/review': typeof StudyDeckIdReviewRoute
  '/study/$deckId/typing': typeof StudyDeckIdTypingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/review': typeof ReviewRoute
  '/deck/$deckId': typeof DeckDeckIdRoute
  '/study/$deckId/flashcard': typeof StudyDeckIdFlashcardRoute
  '/study/$deckId/quiz': typeof StudyDeckIdQuizRoute
  '/study/$deckId/review': typeof StudyDeckIdReviewRoute
  '/study/$deckId/typing': typeof StudyDeckIdTypingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/review': typeof ReviewRoute
  '/deck/$deckId': typeof DeckDeckIdRoute
  '/study/$deckId/flashcard': typeof StudyDeckIdFlashcardRoute
  '/study/$deckId/quiz': typeof StudyDeckIdQuizRoute
  '/study/$deckId/review': typeof StudyDeckIdReviewRoute
  '/study/$deckId/typing': typeof StudyDeckIdTypingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/import'
    | '/review'
    | '/deck/$deckId'
    | '/study/$deckId/flashcard'
    | '/study/$deckId/quiz'
    | '/study/$deckId/review'
    | '/study/$deckId/typing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/import'
    | '/review'
    | '/deck/$deckId'
    | '/study/$deckId/flashcard'
    | '/study/$deckId/quiz'
    | '/study/$deckId/review'
    | '/study/$deckId/typing'
  id:
    | '__root__'
    | '/'
    | '/import'
    | '/review'
    | '/deck/$deckId'
    | '/study/$deckId/flashcard'
    | '/study/$deckId/quiz'
    | '/study/$deckId/review'
    | '/study/$deckId/typing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImportRoute: typeof ImportRoute
  ReviewRoute: typeof ReviewRoute
  DeckDeckIdRoute: typeof DeckDeckIdRoute
  StudyDeckIdFlashcardRoute: typeof StudyDeckIdFlashcardRoute
  StudyDeckIdQuizRoute: typeof StudyDeckIdQuizRoute
  StudyDeckIdReviewRoute: typeof StudyDeckIdReviewRoute
  StudyDeckIdTypingRoute: typeof StudyDeckIdTypingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck/$deckId': {
      id: '/deck/$deckId'
      path: '/deck/$deckId'
      fullPath: '/deck/$deckId'
      preLoaderRoute: typeof DeckDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/$deckId/typing': {
      id: '/study/$deckId/typing'
      path: '/study/$deckId/typing'
      fullPath: '/study/$deckId/typing'
      preLoaderRoute: typeof StudyDeckIdTypingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/$deckId/review': {
      id: '/study/$deckId/review'
      path: '/study/$deckId/review'
      fullPath: '/study/$deckId/review'
      preLoaderRoute: typeof StudyDeckIdReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/$deckId/quiz': {
      id: '/study/$deckId/quiz'
      path: '/study/$deckId/quiz'
      fullPath: '/study/$deckId/quiz'
      preLoaderRoute: typeof StudyDeckIdQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/$deckId/flashcard': {
      id: '/study/$deckId/flashcard'
      path: '/study/$deckId/flashcard'
      fullPath: '/study/$deckId/flashcard'
      preLoaderRoute: typeof StudyDeckIdFlashcardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImportRoute: ImportRoute,
  ReviewRoute: ReviewRoute,
  DeckDeckIdRoute: DeckDeckIdRoute,
  StudyDeckIdFlashcardRoute: StudyDeckIdFlashcardRoute,
  StudyDeckIdQuizRoute: StudyDeckIdQuizRoute,
  StudyDeckIdReviewRoute: StudyDeckIdReviewRoute,
  StudyDeckIdTypingRoute: StudyDeckIdTypingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
